package com.taotao.manage.mapper;

import com.taotao.manage.pojo.ItemDesc;
import com.taotao.manage.pojo.ItemDescExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_desc
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    long countByExample(ItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_desc
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    int deleteByExample(ItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_desc
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_desc
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    int insert(ItemDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_desc
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    int insertSelective(ItemDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_desc
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    List<ItemDesc> selectByExampleWithBLOBs(ItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_desc
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    List<ItemDesc> selectByExample(ItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_desc
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    ItemDesc selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_desc
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") ItemDesc record, @Param("example") ItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_desc
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") ItemDesc record, @Param("example") ItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_desc
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    int updateByExample(@Param("record") ItemDesc record, @Param("example") ItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_desc
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    int updateByPrimaryKeySelective(ItemDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_desc
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(ItemDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_desc
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    int updateByPrimaryKey(ItemDesc record);
}