package com.taotao.manage.mapper;

import com.taotao.manage.pojo.OrderShipping;
import com.taotao.manage.pojo.OrderShippingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_shipping
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    long countByExample(OrderShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_shipping
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    int deleteByExample(OrderShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_shipping
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_shipping
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    int insert(OrderShipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_shipping
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    int insertSelective(OrderShipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_shipping
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    List<OrderShipping> selectByExample(OrderShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_shipping
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    OrderShipping selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_shipping
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") OrderShipping record, @Param("example") OrderShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_shipping
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    int updateByExample(@Param("record") OrderShipping record, @Param("example") OrderShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_shipping
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    int updateByPrimaryKeySelective(OrderShipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_shipping
     *
     * @mbg.generated Tue Jun 27 10:37:42 CST 2017
     */
    int updateByPrimaryKey(OrderShipping record);
}